import { spawnSync } from "node:child_process";
import {
  existsSync,
  lstatSync,
  mkdirSync,
  readFileSync,
  realpathSync,
  writeFileSync,
} from "node:fs";
import { dirname, join, parse, resolve } from "node:path";

import {
  executableInvocation,
  resolveExecutable,
} from "./executable.mjs";

const SAFE_NPM_SCRIPTS = [
  "build",
  "check",
  "docs:check",
  "lint",
  "protocol:check",
  "test:coverage",
  "test:package",
  "verify:commit",
];

export class ProjectRulesError extends Error {
  constructor(code, message) {
    super(message);
    this.name = "ProjectRulesError";
    this.code = code;
  }
}

export function initializeProjectRules({ cwd = process.cwd(), force = false } = {}) {
  return initializeProjectRulesAtRoot({
    projectRoot: findProjectRoot(cwd),
    force,
  });
}

export function initializeProjectRulesAtRoot({ projectRoot, force = false }) {
  const resolvedRoot = realpathSync(resolve(projectRoot));
  const rulesPath = safeRulesPath(resolvedRoot);
  if (existsSync(rulesPath) && !force) {
    throw new ProjectRulesError(
      "exists",
      `项目规则已存在：${rulesPath}\n如需覆盖，请运行 codexc rules init --force`,
    );
  }

  const packageScripts = readPackageScripts(resolvedRoot);
  const content = renderRules(packageScripts);
  mkdirSync(dirname(rulesPath), { recursive: true });
  writeFileSync(rulesPath, content, { mode: 0o644 });
  return { projectRoot: resolvedRoot, rulesPath };
}

export function checkProjectRules({
  cwd = process.cwd(),
  codexBinary = process.env.CODEX_BINARY?.trim() || "codex",
  quiet = false,
} = {}) {
  return checkProjectRulesAtRoot({
    projectRoot: findProjectRoot(cwd),
    codexBinary,
    quiet,
  });
}

export function checkProjectRulesAtRoot({
  projectRoot,
  codexBinary = process.env.CODEX_BINARY?.trim() || "codex",
  quiet = false,
}) {
  const resolvedRoot = realpathSync(resolve(projectRoot));
  const unresolvedRulesPath = safeRulesPath(resolvedRoot);
  if (!existsSync(unresolvedRulesPath)) {
    throw new ProjectRulesError(
      "missing",
      `尚未生成项目规则：${unresolvedRulesPath}\n请先运行 codexc rules init`,
    );
  }
  const rulesPath = realpathSync(unresolvedRulesPath);
  const invocation = executableInvocation(resolveExecutable(codexBinary), [
    "execpolicy",
    "check",
    "--pretty",
    "--rules",
    rulesPath,
    "--",
    "git",
    "status",
    "-sb",
  ]);
  const result = spawnSync(invocation.file, invocation.args, {
    cwd: resolvedRoot,
    env: process.env,
    stdio: quiet ? "ignore" : "inherit",
    windowsVerbatimArguments: invocation.windowsVerbatimArguments,
  });
  if (result.error) {
    throw result.error;
  }
  if (result.signal) {
    throw new ProjectRulesError(
      "check-signaled",
      `项目 Codex 规则检查被信号终止：${result.signal}`,
    );
  }
  if (result.status !== 0) {
    throw new ProjectRulesError(
      "check-failed",
      `项目 Codex 规则检查失败：exit=${result.status ?? 1}`,
    );
  }
  return { projectRoot: resolvedRoot, rulesPath };
}

function safeRulesPath(projectRoot) {
  const codexDirectory = join(projectRoot, ".codex");
  const rulesDirectory = join(codexDirectory, "rules");
  const rulesPath = join(rulesDirectory, "default.rules");
  for (const candidate of [codexDirectory, rulesDirectory, rulesPath]) {
    if (existsSync(candidate) && lstatSync(candidate).isSymbolicLink()) {
      throw new ProjectRulesError(
        "unsafe-path",
        `项目规则路径不能使用符号链接：${candidate}`,
      );
    }
  }
  return rulesPath;
}

function findProjectRoot(cwd) {
  let current = realpathSync(resolve(cwd));
  const root = parse(current).root;
  while (true) {
    if (existsSync(join(current, ".git")) || existsSync(join(current, "package.json"))) {
      return current;
    }
    if (current === root) {
      return realpathSync(resolve(cwd));
    }
    current = dirname(current);
  }
}

function readPackageScripts(projectRoot) {
  const packagePath = join(projectRoot, "package.json");
  if (!existsSync(packagePath)) {
    return {};
  }
  const document = JSON.parse(readFileSync(packagePath, "utf8"));
  return document && typeof document === "object"
    && document.scripts && typeof document.scripts === "object"
    && !Array.isArray(document.scripts)
    ? document.scripts
    : {};
}

function renderRules(packageScripts) {
  const sections = [
    renderGitRule(),
    renderGitInspectionRule(),
    renderChannelImageRule(),
  ];
  if (typeof packageScripts.test === "string") {
    sections.push(renderNpmTestRule());
  }
  const safeScripts = SAFE_NPM_SCRIPTS.filter((name) => typeof packageScripts[name] === "string");
  if (safeScripts.length > 0) {
    sections.push(renderNpmRunRule(safeScripts));
  }
  return [
    "# Generated by `codexc rules init`.",
    "# Codex loads this file only when this project's `.codex` layer is trusted.",
    "",
    sections.join("\n\n"),
    "",
  ].join("\n");
}

function renderGitRule() {
  return `prefix_rule(
    pattern = ["git", ["status", "diff", "log"]],
    decision = "allow",
    justification = "Read-only Git inspection is safe in this project",
    match = [
        "git status",
        "git status -s",
        "git status -sb",
        "git diff",
        "git diff --stat",
        "git diff --cached",
        "git diff --cached --check",
        "git diff --check",
        "git log",
        "git log --oneline",
        "git log -1 --oneline",
        "git log -3 --oneline",
    ],
    not_match = [
        "git add README.md",
        "git commit -m test",
        "git push",
    ],
)`;
}

function renderGitInspectionRule() {
  return `prefix_rule(
    pattern = ["git", ["branch", "remote"]],
    decision = "allow",
    justification = "Read-only branch and remote inspection is safe in this project",
    match = [
        "git branch --list",
        "git branch -a",
        "git remote -v",
    ],
)`;
}

function renderChannelImageRule() {
  return `prefix_rule(
    pattern = ["codexc", "channel", "send-image"],
    decision = "allow",
    justification = "Send a validated local image to the bound Feishu/WeChat/Telegram conversation through the gateway spool",
    match = [
        "codexc channel send-image",
    ],
    not_match = [
        "codexc channel",
    ],
)`;
}

function renderNpmTestRule() {
  return `prefix_rule(
    pattern = ["npm", "test"],
    decision = "allow",
    justification = "Run this project's test suite",
    match = [
        "npm test",
        "npm test -- --run tests/example.test.ts",
    ],
    not_match = [
        "npm install",
        "npm publish",
    ],
)`;
}

function renderNpmRunRule(scriptNames) {
  const names = scriptNames.map((name) => JSON.stringify(name)).join(", ");
  const matches = scriptNames.map((name) => `        "npm run ${name}",`).join("\n");
  return `prefix_rule(
    pattern = ["npm", "run", [${names}]],
    decision = "allow",
    justification = "Run a version-controlled project verification script",
    match = [
${matches}
    ],
    not_match = [
        "npm run dev",
        "npm run hooks:install",
        "npm run release",
    ],
)`;
}
