export type UserFacingErrorCode =
  | "message.empty"
  | "conversation.name.invalid"
  | "conversation.missing"
  | "conversation.busy"
  | "conversation.background-limit"
  | "conversation.background-queued"
  | "image.path.invalid"
  | "image.too-large"
  | "image.too-many"
  | "image.unsupported"
  | "vision.busy"
  | "vision.failed"
  | "vision.retry.missing"
  | "vision.command.usage"
  | "vision.prompt.invalid"
  | "vision.prompt.capacity"
  | "vision.collection.active"
  | "vision.collection.missing"
  | "vision.collection.empty"
  | "vision.collection.count.invalid"
  | "vision.collection.count.exceeded"
  | "audio.path.invalid"
  | "audio.duration-missing"
  | "audio.too-large"
  | "audio.unsupported"
  | "model.input.audio.unsupported"
  | "model.input.image.unsupported"
  | "model.input.unsupported"
  | "session.selector.required"
  | "session.selector.ambiguous"
  | "session.selector.not-found"
  | "sessions.usage"
  | "archived-sessions.usage"
  | "thread-section.usage"
  | "thread-section.name.invalid"
  | "thread-section.selector.ambiguous"
  | "thread-section.selector.not-found"
  | "thread-section.pinned.immutable"
  | "thread-section.before.invalid"
  | "thread-section.delete-confirmation.invalid"
  | "thread-section.admin-required"
  | "thread.bound"
  | "thread.takeover.busy"
  | "thread.takeover.workspace"
  | "thread.takeover.changed"
  | "goal.empty"
  | "goal.usage"
  | "release.usage"
  | "release.unsupported"
  | "queue.usage"
  | "metrics.usage"
  | "queue.inactive"
  | "queue.full"
  | "queue.thread-changed"
  | "workspace.missing"
  | "workspace.selector.required"
  | "workspace.selector.ambiguous"
  | "workspace.selector.not-found"
  | "workspace.permission.usage"
  | "workspace.permission.conflict"
  | "workspace.permission.unavailable"
  | "model.current.missing"
  | "model.configured-default.missing"
  | "model.unavailable"
  | "model.selector.required"
  | "model.selector.ambiguous"
  | "model.selector.not-found"
  | "effort.unsupported"
  | "fast.usage"
  | "fast.unsupported"
  | "provider.account.unavailable"
  | "collaboration-mode.unsupported"
  | "collaboration-mode.unavailable"
  | "plan.prompt.empty"
  | "skill.usage"
  | "skill.not-found"
  | "mcp.usage"
  | "mcp.server.usage"
  | "mcp.server.not-found"
  | "mcp.oauth.unsupported"
  | "mcp.thread.required"
  | "mcp.resource.usage"
  | "plugin.usage"
  | "plugin.not-found"
  | "plugin.ambiguous"
  | "plugin.unavailable"
  | "plugin.disabled"
  | "plugin.provider.unsupported"
  | "agents.usage"
  | "agents.not-found"
  | "agents.config-unreadable"
  | "command.unsupported"
  | "review.usage"
  | "rules.usage"
  | "rules.exists"
  | "rules.missing"
  | "rules.unsafe-path"
  | "rules.check-failed"
  | "rules.unavailable";

export type UserFacingErrorDetails = Readonly<
  Record<string, string | readonly string[]>
>;

export class UserFacingError extends Error {
  constructor(
    readonly code: UserFacingErrorCode,
    message: string,
    readonly details: UserFacingErrorDetails = {},
  ) {
    super(message);
    this.name = "UserFacingError";
  }
}
